title: PEMC Conference Deadlines # (Maintained by @milletbig)
# email: cledewang@xtu.edu.cn
description: Countdowns to top PE/MC conference deadlines.
author: Shawn

domain: "notes.pemcdeadlines.ml"
baseurl: ""

twitter_username: hi_shawnn
github_username: milletbig
github_repo: pemc-deadlines

markdown: kramdown
ga_id: UA-36274081-2

include: ['_pages']
theme: jekyll-theme-slate
