title: PEMC Conference Deadlines # (Maintained by @chyelang)
# email: zouxm16@mails.tsinghua.edu.cn
description: Countdowns to top PE/MC conference deadlines.
author: chyelang

domain: "notes.pemcdeadlines.ml"
baseurl: ""

twitter_username: abhshkdz
github_username: chyelang
github_repo: pemc-deadlines

markdown: kramdown
ga_id: UA-36274081-2

include: ['_pages']
theme: jekyll-theme-slate
